---

- name: Configure jails
  hosts: pegasus.bayofrum.net
  become: true
  tasks:
  - name: add jail.conf.d
    ansible.builtin.file:
      path: '/etc/jail.conf.d'
      state: directory
      mode: '0755'
  - name: add jail config files
    ansible.builtin.template:
      src: "../../templates/jail.conf.d/{{ item }}"
      dest: "/etc/jail.conf.d/{{ item }}"
      owner: root
      group: wheel
      mode: '0644'
    loop:
      - 'dc.conf'
      - 'nc.conf'
      - 'hass14.conf'
      - 'mail.conf'
      - 'mosquitto.conf'
  - name: enable jail rc.conf
    community.general.sysrc:
      name: 'jail_enable'
      value: "yes"
# Need to do this by hand as it doesn't work currently
#  - name: enable jails
#    community.general.sysrc:
#      name: 'jail_list'
#      value_present: '{{ item }}'
#    loop:
#      - nc
  - name: enable aliases
    community.general.sysrc:
      name: 'ifconfig_re0_alias{{ item.alias }}'
      value: 'inet {{ item.ip }} netmask 255.255.255.0'
    loop:
      - { alias: '0', ip: '192.168.1.50' }
      - { alias: '1', ip: '192.168.1.51' }
      - { alias: '2', ip: '192.168.1.52' }
      - { alias: '3', ip: '192.168.1.53' }
      - { alias: '4', ip: '192.168.1.54' }
  - name: start jail
    ansible.builtin.service:
      name: jail
      state: started
