---

- ansible.builtin.import_playbook: playbooks/bayofrum/pkg.yml
- ansible.builtin.import_playbook: playbooks/bayofrum/all_pkgs.yml
#- ansible.builtin.import_playbook: playbooks/bayofrum/pkg_base.yml
- ansible.builtin.import_playbook: playbooks/bayofrum/sudo.yml
- ansible.builtin.import_playbook: playbooks/bayofrum/runit.yml
- ansible.builtin.import_playbook: playbooks/bayofrum/sshd.yml
- ansible.builtin.import_playbook: playbooks/bayofrum/ntpd.yml
- ansible.builtin.import_playbook: playbooks/bayofrum/periodic_ansible_pull.yml
- ansible.builtin.import_playbook: playbooks/bayofrum/cron.yml
- ansible.builtin.import_playbook: playbooks/internal/sssd.yml

- ansible.builtin.import_playbook: playbooks/webserver/apache24.yml
- ansible.builtin.import_playbook: playbooks/webserver/mysql-server.yml
#- ansible.builtin.import_playbook: playbooks/grist/grist.yml
#- ansible.builtin.import_playbook: playbooks/jailer/jail.yml
- ansible.builtin.import_playbook: playbooks/macbook/macbook.yml
- ansible.builtin.import_playbook: playbooks/syncthing/syncthing.yml
- ansible.builtin.import_playbook: playbooks/openemr/openemr.yml
- ansible.builtin.import_playbook: playbooks/nameserver/bind.yml
#- ansible.builtin.import_playbook: playbooks/nextcloud/nextcloud_deps.yml
#- ansible.builtin.import_playbook: playbooks/nextcloud/redis.yml
#- ansible.builtin.import_playbook: playbooks/nextcloud/onlyoffice.yml
- ansible.builtin.import_playbook: playbooks/mailserver/roundcube.yml
- ansible.builtin.import_playbook: playbooks/homeassistant/hass_pkg.yml
- ansible.builtin.import_playbook: playbooks/dc/dc.yml
- ansible.builtin.import_playbook: workstation.yml
- ansible.builtin.import_playbook: linux.yml
