plugin {
    sieve_plugins = sieve_imapsieve sieve_extprograms
    sieve_global_extensions = +vnd.dovecot.pipe +vnd.dovecot.environment

    imapsieve_mailbox1_name = spam-mail-*
    imapsieve_mailbox1_causes = COPY
    imapsieve_mailbox1_before = file:/usr/local/etc/dovecot/imap_sieve.d/queue_spam.sieve

    imapsieve_mailbox2_name = *
    imapsieve_mailbox2_from = spam-mail-*
    imapsieve_mailbox2_causes = COPY
    imapsieve_mailbox2_before = file:/usr/local/etc/dovecot/imap_sieve.d/queue_ham.sieve

    imapsieve_mailbox3_name = *
    imapsieve_mailbox3_from = Junk
    imapsieve_mailbox3_causes = COPY
    imapsieve_mailbox3_before = file:/usr/local/etc/dovecot/imap_sieve.d/queue_ham.sieve

    imapsieve_mailbox4_name = Archive*
    imapsieve_mailbox4_causes = COPY
    imapsieve_mailbox4_before = file:/usr/local/etc/dovecot/imap_sieve.d/queue_ham.sieve

    sieve_pipe_bin_dir = /usr/local/etc/dovecot/imap_sieve.d/
}
