---

- name: install and activate poudriere
  hosts: package_builder
  become: true
  tasks:
  - name: install poudriere
    pkgng:
      name: poudriere ccache
  - name: configure poudriere
    ansible.builtin.template:
      src: ../../templates/poudriere/poudriere.conf
      dest: /usr/local/etc/poudriere.conf
      owner: root
      group: wheel
      mode: '0644'
  - name: make sure filesystems are created
    ansible.builtin.command:
      cmd: /usr/local/bin/poudriere jail -l
      creates: /fast/poudriere
  - name: create directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      mode: 0755
    loop:
      - /exports/src
      - /fast/poudriere/ccache
      - /space/poudriere_data/packages
      - /space/poudriere_data/packages/pkgbase
      - /space/poudriere_data/scripts
  - name: copy script for periodic running
    ansible.builtin.template:
      src: "../../templates/poudriere/{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: wheel
      mode: '0755'
    loop:
      - { src: svsync, dest: /root/svsync }
      - { src: upgradeall.sh, dest: /root/upgradeall/upgradeall.sh }
      - { src: poudriere.d/make.conf, dest: /usr/local/etc/poudriere.d/make.conf }
      - { src: poudriere_cron, dest: /etc/cron.d/poudriere }
      - { src: poudriere.d/pkglist-FreeBSD, dest: /usr/local/etc/poudriere.d/pkglist-FreeBSD }
      - { src: poudriere.d/pkglist-FreeBSD-homeassistant, dest: /usr/local/etc/poudriere.d/pkglist-FreeBSD-homeassistant }
      - { src: poudriere.d/pkglist-FreeBSD-mosquitto, dest: /usr/local/etc/poudriere.d/pkglist-FreeBSD-mosquitto }
      - { src: poudriere.d/pkglist-FreeBSD-server, dest: /usr/local/etc/poudriere.d/pkglist-FreeBSD-server }
      - { src: poudriere.d/pkglist-FreeBSD-webserver, dest: /usr/local/etc/poudriere.d/pkglist-FreeBSD-webserver }
      - { src: poudriere.d/pkglist-FreeBSD-workstation, dest: /usr/local/etc/poudriere.d/pkglist-FreeBSD-workstation }
  - name: add links for packages for webserver
    ansible.builtin.file:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
      state: link
    loop:
      - { src: /space/poudriere_data/packages, dest: /usr/local/www/data/pkg_download }
      - { src: /space/poudriere_data/logs/bulk, dest: /usr/local/www/data/pkg }
