---

- name: install workstation pkgs
  hosts: workstation
  become: true
  tasks:
  - name: install workstation pkgs
    pkgng:
      name: "{{ lookup('file', '../../pkglists/FreeBSD-workstation') }}"
