---

- name: install relevant pkgs
  hosts: bayofrum
  become: true
  tasks:
  - name: install relevant pkgs
    community.general.pkgng:
      name: "{{ lookup('file', '../../templates/poudriere/poudriere.d/pkglist-FreeBSD') }}"
