---

- name: install and upgrade FreeBSD base
  hosts: none
  become: true
  vars:
    basepkg_list: "{{ lookup('file', '../../pkglists/FreeBSD-base') | split('\n') | join(' ') }}"
    srl: 1322
  tasks:
  - name: upgrade FreeBSD base
    ansible.builtin.script:
      creates: '/var/db/ansible/pkg_base/serial/{{ srl }}'
      cmd: ../../scripts/FreeBSD-base-upgrade '{{ srl }}' FreeBSD:14:amd64 14.1 '{{ basepkg_list }}'
