---

- name: install and activate BIND
  hosts: mosquitto
  vars:
    srv: mosquitto
  become: true
  tasks:
  - name: install {{ srv }}
    pkgng:
      name: '{{ srv }}'
  - name: add {{ srv }} runsv directory
    ansible.builtin.file:
      path: '/etc/sv/{{ srv }}'
      state: directory
      mode: '0755'
  - name: add {{ srv }} runsv file
    ansible.builtin.template:
      src: '../../templates/runit/{{ srv }}_run'
      dest: '/etc/sv/{{ srv }}/run'
      owner: root
      group: wheel
      mode: '0755'
  - name: configure {{ srv }}
    ansible.builtin.lineinfile:
      dest: /usr/local/etc/mosquitto/mosquitto.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    loop:
      - { regexp: '^#?pid_file', line: '#pid_file /var/run/mosquitto.pid' }
      - { regexp: '^#?listener', line: 'listener 1883 mosquitto.bayofrum.net' }
      - { regexp: '^#?password_file', line: 'password_file /usr/local/etc/mosquitto/pwfile' }
  - name: enable {{ srv }} boot
    ansible.builtin.file:
      src: '/etc/sv/{{ srv }}'
      dest: '/var/service/{{ srv }}'
      state: link
